sources:
  BCC_CSM2_MR:
    args:
      path: 'BCC_CSM2_MR/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}
    
  CNRM_CM6_1:
    args:
      path: 'CNRM_CM6_1/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}

  CNRM_ESM2_1:
    args:
      path: 'CNRM_ESM2_1/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}

  GISS_E2_1_G:
    args:
      path: 'GISS_E2_1_G/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}

  IPSL_CM6A_LR:
    args:
      path: 'IPSL_CM6A_LR/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}
