sources:
  r1i1p1f2:
    args:
      path: 'CNRM_CM6_1/historical/r1i1p1f2/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}

  r2i1p1f2:
    args:
      path: 'CNRM_CM6_1/historical/r2i1p1f2/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}
