sources:
  r1i1p1f1:
    args:
      path: '{{ CATALOG_DIR }}/r1i1p1f1/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}

  r2i1p1f1:
    args:
      path: '{{ CATALOG_DIR }}/r2i1p1f1/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}

  r3i1p1f1:
    args:
      path: '{{ CATALOG_DIR }}/r3i1p1f1/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}

  r4i1p1f1:
    args:
      path: '{{ CATALOG_DIR }}/r4i1p1f1/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}

  r5i1p1f1:
    args:
      path: '{{ CATALOG_DIR }}/r5i1p1f1/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}

  r6i1p1f1:
    args:
      path: '{{ CATALOG_DIR }}/r6i1p1f1/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}

  r7i1p1f1:
    args:
      path: '{{ CATALOG_DIR }}/r7i1p1f1/config.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}
